package com.tweetapp.tweet.model;

import java.time.LocalDateTime;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.tweetapp.tweet.converter.DateTimeConverter;
import com.tweetapp.tweet.converter.LikesConverter;
import com.tweetapp.tweet.converter.ReplyConverter;

//@Getter
//@Setter
//@NoArgsConstructor
//@ToString
////@Document
@DynamoDBTable(tableName = "tweets")
public class Tweet {

	// @Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String tweetId;

	@DynamoDBAttribute
	private String tweet;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = ReplyConverter.class)
	private List<TweetReply> reply;

	@DynamoDBAttribute
	private String userName;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LikesConverter.class)
	private List<String> likes;

	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = DateTimeConverter.class)
	private LocalDateTime date;
//	@DynamoDBAttribute
//	private String date;

	public String getTweetId() {
		return tweetId;
	}

	public void setTweetId(String tweetId) {
		this.tweetId = tweetId;
	}

	public String getTweet() {
		return tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public List<TweetReply> getReply() {
		return reply;
	}

	public void setReply(List<TweetReply> reply) {
		this.reply = reply;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public List<String> getLikes() {
		return likes;
	}

	public void setLikes(List<String> likes) {
		this.likes = likes;
	}

	public LocalDateTime getDate() {
		return date;
	}

	public void setDate(LocalDateTime date) {
		this.date = date;
	}

	public Tweet() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Tweet(String tweetId, String tweet, List<TweetReply> reply, String userName, List<String> likes,
			LocalDateTime date) {
		super();
		this.tweetId = tweetId;
		this.tweet = tweet;
		this.reply = reply;
		this.userName = userName;
		this.likes = likes;
		this.date = date;
	}

	@Override
	public String toString() {
		return "Tweet [tweetId=" + tweetId + ", tweet=" + tweet + ", reply=" + reply + ", userName=" + userName
				+ ", likes=" + likes + ", date=" + date + "]";
	}

}
